on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  notify:
    name: Notify
    runs-on: ubuntu-latest
    steps:
      - name: Send release notification
        uses: slackapi/slack-github-action@485a9d42d3a73031f12ec201c457e2162c45d02d # v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: webhook-trigger
          payload: |
            repo: "${{ github.repository }}"
            url: "${{ github.event.release.html_url }}"
            version: "${{ github.event.release.tag_name }}"
